export const genres = [
  { id: 'action', displayName: 'Action' },
  { id: 'adventure', displayName: 'Adventure' },
  { id: 'animation', displayName: 'Animation' },
  { id: 'biography', displayName: 'Biography' },
  { id: 'comedy', displayName: 'Comedy' },
  { id: 'crime', displayName: 'Crime' },
  { id: 'documentary', displayName: 'Documentary' },
  { id: 'drama', displayName: 'Drama' },
  { id: 'family', displayName: 'Family' },
  { id: 'fantasy', displayName: 'Fantasy' },
  { id: 'film_noir', displayName: 'Film Noir' },
  { id: 'game_show', displayName: 'Game Show' },
  { id: 'history', displayName: 'History' },
  { id: 'horror', displayName: 'Horror' },
  { id: 'music', displayName: 'Music' },
  { id: 'musical', displayName: 'Musical' },
  { id: 'mystery', displayName: 'Mystery' },
  { id: 'news', displayName: 'News' },
  { id: 'reality_tv', displayName: 'Reality TV' },
  { id: 'romance', displayName: 'Romance' },
  { id: 'sci_fi', displayName: 'Sci-Fi' },
  { id: 'sport', displayName: 'Sport' },
  { id: 'talk_show', displayName: 'Talk Show' },
  { id: 'thriller', displayName: 'Thriller' },
  { id: 'war', displayName: 'War' },
  { id: 'western', displayName: 'Western' },
];
